Laird device
actility/device-catalog pull request #116
Opened 2024-02-16 21:36 UTC by vascode

Updated device names displayed in Actility's web UI for registering devices. 
Updated driver directory to add decoders.

2024-02-29 12:57 UTC, tomHallActility requested changes
Hi Seokwoo,

Thank you for making this pull request. I reviewed it and requested a few modifications.
Please take the time to go through each of them.

Thank you in advance.
Have a great day.

Best regards,
Tom

2024-02-29 12:57 UTC, tomHallActility commented on vendors/laird/drivers/ext-multi/index.js
Please add the following at the end of this file for the lora-alliance functions to be exported:
exports.decodeUplink = decodeUplink;
exports.encodeDownlink = encodeDownlink;
exports.decodeDownlink = decodeDownlink;

**If you wish to keep the driver with the current protocolId "os1-lair:rs1xx-ext-multi:1" as an option for your customers**, you would have to have to change the driver folder's name (to something like ext-multi2) and recreate a folder named "ext-multi" with the current driver.yaml file (specifying "os1-lair:rs1xx-ext-multi:1" as a protocolId). 
**Otherwise you can ignore this paragraph**.

Also, **regarding the driver.yaml file**, this one corresponds to one of our private driver. If this new driver replaces the previous one for the Ext Multi device model, please replace driver.yaml with a template that you'll find in "./template/sample-vendor/drivers/sample-driver" and modify the information accordingly.
The protocolId cannot be the same as the one it is currently set to.
I suggest using laird:ext-multi:1 as a protocolId.

After doing that, don't forget to update the list of protocolIds in your device model's model.yaml file.

2024-02-29 12:57 UTC, tomHallActility commented on vendors/laird/drivers/ext-multi/examples/temp-rh.examples.json
The examples work fine, however we expect a minimum test coverage of 85% to be valid on our framework.
If you could add examples to reach that percentage that would be great, thank you.

2024-02-29 12:57 UTC, tomHallActility commented on vendors/laird/drivers/ext-temp-rtd/index.js
Same as for the ext-multi driver, please add the following at the end of this file:
exports.decodeUplink = decodeUplink;
exports.encodeDownlink = encodeDownlink;
exports.decodeDownlink = decodeDownlink;

Same comment as for the ext-multi driver, please change the driver.yaml using a template and update the protocolId list on the models using this driver.
Thank you in advance.

2024-02-29 12:57 UTC, tomHallActility commented on vendors/laird/drivers/ext-temp-rtd/examples/ext-temp-1w.examples.json
Here, I am not sure why, but 7 of the 24 examples fail (some temperature values change and humidity doesn't appear in the decoder outputs, some other examples have errors: ["Invalid message type used!"]).
Please check that your examples are valid, and as with the other driver, please try to reach a percentage of 85% of test coverage. Thank you in advance.

2024-04-11 22:26 UTC, vascode commented on vendors/laird/drivers/ext-multi/index.js
I don't know what version of driver you have in your private repository. If it it same, I guess it does not need to be updated.

2024-04-11 22:31 UTC, vascode commented on vendors/laird/drivers/ext-multi/examples/temp-rh.examples.json
Isn't example just example uplink packet received (in json) in your server? We have so many different message types for up/downlink data that can be formed (https://www.ezurio.com/documentation/application-note-rs1xx-lora-protocol). Do you mean that we should test 85% of all the available message type we can generate and get example packet as output?  Also, I don't have Actility account so could you help me to create my account if needed?

2024-04-12 09:29 UTC, tomHallActility requested changes
Hi,

Thank you for your updates.
Please find the new comments I made on our pull request.

Thank you in advance,
Tom

2024-04-12 09:29 UTC, tomHallActility commented on vendors/laird/drivers/ext-multi/examples/temp-rh.examples.json
Sorry for the confusion. What we mean by 85% coverage is using jest by running "npm install" and "npm run test" inside your driver's folder.

However, your index.js files are missing exports to be able to use your codec functions.
Please add the following at the end of your index.js files:
exports.decodeUplink = decodeUplink;
exports.encodeDownlink = encodeDownlink;
exports.decodeDownlink = decodeDownlink;

2024-04-12 09:29 UTC, tomHallActility commented on vendors/laird/drivers/ext-multi/index.js
The driver.yaml that is currently inside the drivers/ext-multi folder is just a reference to link with the driver in our private repository. 
Note that the driver in our private repository and your new driver are different codecs and may not have a reference to the same protocolId.

In order for our mutual customer to benefit from the use of both drivers (the private one as well as the one you are meaning to add), it is important to create a different driver folder for the the driver.yaml "protocolId: os1-lair:rs1xx-ext-multi:1" and cut-paste it there.

A public driver should have a full driver.yaml file that you can find here: ./template/sample-vendor/drivers/sample-driver/driver.yaml, which you can copy-paste inside your new public drivers and modify according to the drivers' information (with their new protocolId).

2024-07-16 16:52 UTC, mostafaibr commented
@tomHallActility , is this PR ready to be merged/closed?

2024-07-19 13:46 UTC, tomHallActility requested changes

2024-07-19 13:46 UTC, tomHallActility commented on vendors/laird/drivers/ext-temp-rtd/examples/ext-temp-1w.examples.json
Hi @vascode ,

It seems some examples are using a message type of 0x01 and 0x06, which are not defined as cases in the switch scope of the decodeUplink function.
I also found that for some reason, the temperatures are exaggeratedly high (for instance 17335 instead of 98.67).
If you need help in correcting your PR, don't hesitate to ask.

Thank you,
Tom

2024-09-19 09:06 UTC, tomHallActility approved these changes

2024-09-19 09:51 UTC, merged