Add Changes
actility/device-catalog pull request #122
Opened 2024-03-14 12:31 UTC by GiorgosM1995

This is the correct changes

2024-03-21 10:10 UTC, tomHallActility requested changes
Hello Cicicom,

Thank you for correcting your original pull request.
Here are a couple more things to change. 
Please take your time to review them.

Thank you very much.

Best regards,
Tom

2024-03-21 10:10 UTC, tomHallActility commented on vendors/cicicom/model/s-lg-i3/model.yaml
Hi Cicicom,

Could you remove the "product" field (including name and version) as they are now deprecated.
Also, please make the modelId lowercase only.

Thank you very much.

2024-03-21 10:10 UTC, tomHallActility commented on vendors/cicicom/profiles/profile.yaml
In order to keep your profiles separate in the future, please rename profile.yaml as "cicicom_RFGroup1_1.0.2a_classA.yaml".
Please change the id in the file as "cicicom_RFGroup1_1.0.2a_classA", as well.

Thank you in advance.

2024-03-28 10:40 UTC, tomHallActility requested changes
Hello Giorgos,

I hope you are doing well.
Thank you for correcting your previous pull request.
There are still a couple of things to change.
Thank you for taking a look at them.

Have a great day,
Tom

2024-03-28 10:40 UTC, tomHallActility commented on vendors/cicicom/model/s-lg-i3/model.yaml
Hi,
I believe there's a small typo line 27: 
icicom:s-lg-i3:2 -> cicicom:s-lg-i3:2

2024-03-28 10:40 UTC, tomHallActility commented on vendors/cicicom/profiles/cicicom_RFGroup1_1.0.2a_classA.yaml
How we link the profiles to the models is through the id field line 11.
Please change:
lora-generic_RFGroup1_1.0.2a_classA
to
cicicom_RFGroup1_1.0.2a_classA
Thank you very much.

2024-04-04 13:05 UTC, tomHallActility requested changes

2024-04-04 13:05 UTC, tomHallActility commented on vendors/cicicom/model/s-lg-i3/model.yaml
Hello Giorgos,

There is still one small correction to make, can you change the protocolId:
protocolId: cicicom:s-lg-i3
to
protocolId: cicicom:s-lg-i3:1

Thank you.

2024-04-04 13:35 UTC, GiorgosM1995 commented on vendors/cicicom/model/s-lg-i3/model.yaml
Hello Tom,
thanks for answering I made the correction

2024-04-04 15:26 UTC, tomHallActility approved these changes

2024-04-04 15:26 UTC, merged