TXIF-2945 - Linking Cicicom private driver to Parking Sensor model
actility/device-catalog pull request #141
Opened 2024-05-16 10:29 UTC by tomHallActility

2024-05-16 11:45 UTC, mostafaibr requested changes

2024-05-16 11:45 UTC, mostafaibr commented on vendors/cicicom/drivers/s-lg-i3/driver.yaml
> +protocolId: cicicom:s-lg-i3:1
```suggestion
# A reference to the corresponding driver on our private drivers repository
protocolId: cicicom:s-lg-i3:1
```

2024-05-17 11:30 UTC, GiorgosM1995 approved these changes

2024-05-21 14:09 UTC, mostafaibr approved these changes

2024-05-21 14:09 UTC, merged