Txif 2998 maddalena/arrow wan2
actility/device-catalog pull request #150
Opened 2024-07-08 12:09 UTC by LenActility

Driver & model for arrowWan2 from Maddalena

2024-07-08 15:30 UTC, LenActility commented on vendors/maddalena/drivers/arrowwan2/index.js
> +/*let input =  {
I forgot to delete debug lines

2024-07-16 16:40 UTC, mostafaibr requested changes

2024-07-16 16:40 UTC, mostafaibr commented on vendors/maddalena/models/arrowwan2/model.yaml
> +
Are there some device profiles missing? Strange to add only model without profiles. Is it requested to be used only with a custom device profile?

2024-07-16 16:40 UTC, mostafaibr commented on vendors/maddalena/models/arrowwan2/model.yaml
> +    version: 1
```suggestion
```

No need for this part in the new device models. It was used before in the already existing devices.

2024-07-16 16:40 UTC, mostafaibr commented on vendors/maddalena/drivers/arrowwan2/package.json
> +  "name": "maddalena-arrowwan2-driver",
```suggestion
  "name": "arrowwan2",
```

2024-07-16 16:51 UTC, mostafaibr requested changes

2024-07-16 16:51 UTC, mostafaibr commented on vendors/maddalena/drivers/arrowwan2/examples.json
> +  {
This example failed on unit tests: 

``` 
● Decode uplink › Hourly readings and alarms (two frames for 24 hour values)

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 12
    + Received  + 12

    @@ -4,66 +4,66 @@
          "measure_vif": 19,
          "readings": Array [
            Object {
              "delta": 0,
              "reading": 172633,
    -         "timestamp": "2022-05-12T11:00:00",
    +         "timestamp": "2022-05-12T13:00:00",
            },
            Object {
              "delta": 3206,
              "reading": 169427,
    -         "timestamp": "2022-05-12T10:00:00",
    +         "timestamp": "2022-05-12T12:00:00",
            },
            Object {
              "delta": 3171,
              "reading": 166256,
    -         "timestamp": "2022-05-12T09:00:00",
    +         "timestamp": "2022-05-12T11:00:00",
            },
            Object {
              "delta": 3114,
              "reading": 163142,
    -         "timestamp": "2022-05-12T08:00:00",
    +         "timestamp": "2022-05-12T10:00:00",
            },
            Object {
              "delta": 3102,
              "reading": 160040,
    -         "timestamp": "2022-05-12T07:00:00",
    +         "timestamp": "2022-05-12T09:00:00",
            },
            Object {
              "delta": 3118,
              "reading": 156922,
    -         "timestamp": "2022-05-12T06:00:00",
    +         "timestamp": "2022-05-12T08:00:00",
            },
            Object {
              "delta": 3117,
              "reading": 153805,
    -         "timestamp": "2022-05-12T05:00:00",
    +         "timestamp": "2022-05-12T07:00:00",
            },
            Object {
              "delta": 3131,
              "reading": 150674,
    -         "timestamp": "2022-05-12T04:00:00",
    +         "timestamp": "2022-05-12T06:00:00",
            },
            Object {
              "delta": 3131,
              "reading": 147543,
    -         "timestamp": "2022-05-12T03:00:00",
    +         "timestamp": "2022-05-12T05:00:00",
            },
            Object {
              "delta": 3121,
              "reading": 144422,
    -         "timestamp": "2022-05-12T02:00:00",
    +         "timestamp": "2022-05-12T04:00:00",
            },
            Object {
              "delta": 3112,
              "reading": 141310,
    -         "timestamp": "2022-05-12T01:00:00",
    +         "timestamp": "2022-05-12T03:00:00",
            },
            Object {
              "delta": 3115,
              "reading": 138195,
    -         "timestamp": "2022-05-12T00:00:00",
    +         "timestamp": "2022-05-12T02:00:00",
            },
          ],
          "timestamp": "2022-05-13T15:59:30",
          "type": "measure",
        },

      218 |                 adaptDates(result, expected);
      219 |
    > 220 |                 expect(result).toStrictEqual(expected);
          |                                ^
      221 |             });
      222 |         }
      223 |     });

      at Object.toStrictEqual (driver-examples.spec.js:220:32)

```

2024-07-16 16:51 UTC, mostafaibr commented on vendors/maddalena/drivers/arrowwan2/examples.json
> +  {
This example failed on unit tests:

```
 ● Decode uplink › Daily readings (7 days) and alarms

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 7
    + Received  + 7

    @@ -4,41 +4,41 @@
          "measure_vif": 19,
          "readings": Array [
            Object {
              "delta": 0,
              "reading": 1700,
    -         "timestamp": "2022-06-26T00:00:00",
    +         "timestamp": "2022-06-26T02:00:00",
            },
            Object {
              "delta": 383,
              "reading": 1317,
    -         "timestamp": "2022-06-25T00:00:00",
    +         "timestamp": "2022-06-25T02:00:00",
            },
            Object {
              "delta": 107,
              "reading": 1210,
    -         "timestamp": "2022-06-24T00:00:00",
    +         "timestamp": "2022-06-24T02:00:00",
            },
            Object {
              "delta": -41,
              "reading": 1251,
    -         "timestamp": "2022-06-23T00:00:00",
    +         "timestamp": "2022-06-23T02:00:00",
            },
            Object {
              "delta": 0,
              "reading": 1251,
    -         "timestamp": "2022-06-22T00:00:00",
    +         "timestamp": "2022-06-22T02:00:00",
            },
            Object {
              "delta": 51,
              "reading": 1200,
    -         "timestamp": "2022-06-21T00:00:00",
    +         "timestamp": "2022-06-21T02:00:00",
            },
            Object {
              "delta": 1200,
              "reading": 0,
    -         "timestamp": "2022-06-20T00:00:00",
    +         "timestamp": "2022-06-20T02:00:00",
            },
          ],
          "timestamp": "2022-06-27T00:00:04",
          "type": "measure",
        },

      218 |                 adaptDates(result, expected);
      219 |
    > 220 |                 expect(result).toStrictEqual(expected);
          |                                ^
      221 |             });
      222 |         }
      223 |     });

      at Object.toStrictEqual (driver-examples.spec.js:220:32)

```

2024-07-17 13:55 UTC, LenActility reviewed
I wrote the driver in device catalog private because I didn't know that if we write our proper driver, we do that in the private catalog

2024-07-18 14:13 UTC, mostafaibr approved these changes

2024-07-18 14:13 UTC, merged