add liebearth devices driver
actility/device-catalog pull request #154
Opened 2024-07-16 09:19 UTC by saidialhaye10

these updates are related to adding liebearth driver.s

2024-07-16 15:10 UTC, mostafaibr requested changes

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/drivers/downlink.schema.json
> +{
This is not a json schema of the downlink, maybe it is an example? Otherwise, the schema is optional, so you can remove this file.

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/drivers/uplink.schema.json
This is not a json schema of the uplink, maybe it is an example? Otherwise, the schema is optional, so you can remove this file.

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/profiles/liebearth_eu_868_class_A.yaml
> +id: liebearth_eui_868_class_A
```suggestion
id: lbearth_RFGroup1_1.0.4_class_A
```

As mentioned in the comment above, this is the right way to identify a profile on our catalog.

After updating do not forget to update the models which use this profile.

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/profiles/liebearth_eu_868_class_C.yaml
> +id: liebearth_eu_868_class_C
```suggestion
id: lbearth_RFGroup1_1.0.4_class_C
```

As mentioned above, this is the right way to identify a profile on our catalog. 

After updating do not forget to update the models which use this profile.

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/models/hub/model.yaml
> +  - id: liebearth_eu_868_class_C
lbearth_RFGroup1_1.0.4_class_C

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/models/latch_manager/model.yaml
> +  - id: liebearth_eu_868_class_A
```suggestion
  - id: lbearth_RFGroup1_1.0.4_class_A

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/models/sensor/model.yaml
> +  - id: liebearth_eu_868_class_A
```suggestion
  - id: lbearth_RFGroup1_1.0.4_class_A
```

2024-07-16 15:10 UTC, mostafaibr commented on vendors/liebearth/drivers/index.js
It is highly recommended to add examples as mentioned in the guide, in order to test this driver before merging it and release a new drivers catalog.

2024-07-16 15:13 UTC, mostafaibr requested changes

2024-07-16 15:13 UTC, mostafaibr commented on vendors/liebearth/drivers/downlink.schema.json
This is not a json schema of the downlink, maybe it is an example? Otherwise, the schema is optional, so you can remove this file.

2024-07-17 08:10 UTC, saidialhaye10 reviewed
Hello Mostafa,

I have updated my driver to comply with your request. I hope I didn't miss anything.

Thank you.

2024-07-18 13:25 UTC, mostafaibr commented
Hello @saidialhaye10 , 

I tried to do the modifications but do not have access to your fork so here are my comments: 

- The driver is a generic one for all your devices. it should be named `generic` instead of `lbearthd`.
Thus, under `/drivers `,  a folder should be created with name "generic" and you put inside all the driver related files (driver.yaml, index.js, examples.json).  (Reference in the guide: [Structure](https://github.com/actility/device-catalog/blob/main/template/README.md#structure)).
- The driver should be an npm package, so a package.json file should be added following our sample. You can simply copy [this file](https://github.com/actility/device-catalog/blob/main/template/sample-vendor/drivers/sample-driver/package.json) and adapt it to your driver generic . (Reference in the guide: [Packaging](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#packaging))
- Based on the code, the driver follows the lora-alliance signature defined in the guide, so please remove the "chirpstack" from "driver.yaml". (Described in the comments of driver.yaml file)
- the `encodeDownlink` should return an object with field "bytes" and not the array of bytes directly (Reference in the guide: [EncodeDownlink](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#downlink-encode))
- `decodeDownlink` is optional, it can be removed or fixed to return the object as expected (Reference in the guide: [DecodeDownlink](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#downlink-decode)).
- Unit tests are needed to be able to accept your PR, You should copy [this spec file](https://github.com/actility/device-catalog/blob/main/template/sample-vendor/drivers/sample-driver/driver-examples.spec.js) (No changes to be done on this file, it is already implemented to test your driver based on the examples you provided in "examples.json") to your "/drivers/generic" folder, and ensure that all tests are passed. (Reference in the guide: [Testing](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#testing))

2024-07-18 13:26 UTC, mostafaibr requested changes
Hello @saidialhaye10  , 

I tried to do the modifications but do not have access to your fork so here are my comments: 

- The driver is a generic one for all your devices. it should be named `generic` instead of `lbearthd`.
Thus, under `/drivers`,  a folder should be created with name "generic" and you put inside all the driver's related files (driver.yaml, index.js, examples.json).  (Reference in the guide: [Structure](https://github.com/actility/device-catalog/blob/main/template/README.md#structure)).
- The driver should be an npm package, so a package.json file should be added following our sample. You can simply copy [this package file](https://github.com/actility/device-catalog/blob/main/template/sample-vendor/drivers/sample-driver/package.json) and adapt it to your driver generic . (Reference in the guide: [Packaging](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#packaging))
- Based on the code, the driver follows the lora-alliance signature defined in the guide, so please remove the "chirpstack" from "driver.yaml". (Described in the comments of driver.yaml file)
- the `encodeDownlink` should return an object with field "bytes" and not the array of bytes directly (Reference in the guide: [EncodeDownlink](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#downlink-encode))
- `decodeDownlink` is optional, it can be removed. Otherwise, it should be fixed to return the object as expected (Reference in the guide: [DecodeDownlink](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#downlink-decode)).
- Unit tests are needed to be able to accept your PR, You should copy [this spec file](https://github.com/actility/device-catalog/blob/main/template/sample-vendor/drivers/sample-driver/driver-examples.spec.js) (No changes to be done on this file, it is already implemented to test your driver based on the examples you provided in "examples.json") to your "/drivers/generic" folder, and ensure that all tests are passed. (Reference in the guide: [Testing](https://github.com/actility/device-catalog/tree/main/template/sample-vendor/drivers#testing))

2024-07-18 15:18 UTC, saidialhaye10 commented
Hello @mostafaibr,

I apologize for not being able to provide something cleaner right away; this is my first time interacting with Actility. However, I have updated my driver to address your request and the tests have been successful.

Thank you for your understanding.

2024-07-19 11:14 UTC, mostafaibr requested changes
Hello @saidialhaye10 , 

No worries, we are here to help. Thank you for the modifications, now the structure of your vendor folder seems perfect. 
There is one remaining issue,Your examples.json does not reflect the actual behavior of your driver. 
Under "/drivers/generic", run `npm install` then `npm run test`. This will test your examples input and compare the actual and expected output described in your example. 
You will see that the unit tests are still failing for two examples out of three.
![image](https://github.com/user-attachments/assets/fc692ed0-dc45-4b53-8f8e-3370f27ba5f7)
 
For liebearth sensor: 
![image](https://github.com/user-attachments/assets/d306b499-e06e-4228-877a-65bc9534f7f4)


For liebearth  latch manager: 
![image](https://github.com/user-attachments/assets/a2ccf249-9f0b-41e1-a2bd-d374fdc54f2c)

2024-07-19 13:15 UTC, mostafaibr approved these changes

2024-07-19 13:16 UTC, merged