Feat/terabee
actility/device-catalog pull request #187
Opened 2024-09-19 12:36 UTC by chrisandoX

Fixed, incorrect device profile settings. Added 2 new products and updated the Terabee commercial information.

2024-10-03 13:05 UTC, tomHallActility requested changes
Hello Terabee,

The examples field in the model.yaml files must be filled with the right protocolId (which is the case) and have the descriptions of the examples (of that driver) you want to associate with your models.
Could you change that? It's the only critical thing I cannot change myself.
Thank you very much.

Best regards,
Tom

2024-10-03 13:05 UTC, tomHallActility commented on vendors/terabee/models/pc-l-xl/model.yaml
Unmatched example description

2024-10-03 13:05 UTC, tomHallActility commented on vendors/terabee/models/tb-pcm/model.yaml
Unmatched example description

2024-10-03 13:05 UTC, tomHallActility commented on vendors/terabee/models/tb-poc/model.yaml
Unmatched example description

2024-10-04 15:23 UTC, chrisandoX commented
Requested changes have been adressed. I've also noticed a device profiles that weren't used hence removed it for clarity.

2024-10-10 08:59 UTC, tomHallActility approved these changes
Thank you for your changes.
I'll merge your branch.
I will still need to change a few necessary technical things myself before we can deploy it.

2024-10-10 08:59 UTC, merged

2024-10-10 10:01 UTC, chrisandoX commented
Thanks!

When do you think it would be ready for deployment, I am looking forward to
test it ;)

BR
Chris

On Thu, Oct 10, 2024 at 10:59 AM tomHallActility ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Thank you for your changes.
> I'll merge your branch.
> I will still need to change a few necessary technical things myself before
> we can deploy it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/actility/device-catalog/pull/187#pullrequestreview-2359569647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADFDL73GQQ55XNPN3Y5DBE3Z2Y6XXAVCNFSM6AAAAABOP2M6LOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJZGU3DSNRUG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-10 10:16 UTC, tomHallActility commented
No problem at all.
We're planning on deploying this afternoon.

Best regards,
Tom