Added support for Quandify CubicMeter 1.1
actility/device-catalog pull request #199
Opened 2024-11-05 15:58 UTC by peter-quandify

2024-11-12 08:47 UTC, peter-quandify commented
Ready for merge

2024-11-21 14:34 UTC, tomHallActility requested changes
Hi Peter,

Thank you for making this Pull Request.
The CubicMeter is in now in two categories, right?
I would suggest instead of deleting the original one, we could just change its name to cubicmeter 1.1 copper and add a new model for the plastic one, to avoid complexifying deployments on our catalogs.
Is that ok with you?

Once that is done, I will merge your PR and make a few adaptations on our side since we'll have all the information we need, and your changes will then be integrated to the next deployments.

Best regards,
Tom

2024-11-21 14:34 UTC, tomHallActility commented on vendors/axioma/drivers/w1/package-lock.json
Could you discard your changes from this file please? Thanks.

2024-11-21 16:17 UTC, peter-quandify commented
Hi Tom,
I changed the modelId in cubicmeter-1.1-copper/model.yml to match the one that was in the cubicmeter folder before.
Was this how you intended the change?

Also removed the axioma from the PR, sorry for that random mistake.

2024-11-21 16:36 UTC, tomHallActility commented
Ok thank you very much.
I'll go ahead and merge that then make a few changes on my part.

2024-11-21 16:36 UTC, tomHallActility approved these changes

2024-11-21 16:37 UTC, merged