Added vendor Enginko
actility/device-catalog pull request #201
Opened 2024-11-12 08:08 UTC by niccoloenginko

Added new products by Enginko, formerly mcf88

2024-11-21 10:08 UTC, tomHallActility requested changes
Hi Niccolo,

Thank you for making this pull request.
After merging your changes with the main branch, I'll go ahead and fix a few things, but we have all the information we need to do that.
In the meantime, I would need you to fix your driver as it seems to be failing (see the comment on examples.json), please.
Once that is done, I can merge it.

Thank you very much.
Best regards,
Tom

2024-11-21 10:08 UTC, tomHallActility commented on vendors/enginko/drivers/level-sensors/examples.json
Hi Niccolo,

The driver's examples are failing because the payloads' uplinkIDs (the first byte in hexadecimal) are not consistent with the switch cases in the code (ex: for the first example, "20" - or 30 in decimal - is not in the cases).
Could you try to fix that please?
Thank you in advance.

Cheers,
Tom

2024-11-26 08:28 UTC, niccoloenginko commented on vendors/enginko/drivers/level-sensors/examples.json
Hi Tom,
I should have fixed the code on my end, but just to be sure on how to proced: do I need to open a new pull request to send you the fixes or there is something else that I should do?

Thanks in advance
Best regards,
Niccolò

2024-11-28 09:48 UTC, tomHallActility commented on vendors/enginko/drivers/level-sensors/examples.json
No worries, all your additional changes appear on GitHub PRs.

2024-11-28 12:48 UTC, tomHallActility requested changes
Hi Niccolo,

The codec is still failing. 
Could you take a look? Thank you.

Best regards,
Tom

2024-11-28 12:48 UTC, tomHallActility commented on vendors/enginko/drivers/level-sensors/examples.json
There is one example that just has a problem of JSON object embedding ("data" should contain the output in the "output" object and "errors" should be in that "output" too), the description of which is "uplink example for IO data (example 2)". I can correct this myself as it's a simple formatting issue.

2024-11-28 12:48 UTC, tomHallActility commented on vendors/enginko/drivers/level-sensors/examples.json
The other failing example is the one right after "uplink example for level data (type 1)". This one's first byte is 14 (in decimal), and its hexadecimal equivalent isn't "0x14" but "0x0E" which does not appear in the switch cases. 

The last example (not failing) starting with 20 (decimal) - which is "0x14" in hexadecimal - does decode correctly.
I suppose the one starting with 14 should start with 20 instead.

Do you agree? could you correct this please?

Thank you in advance,
Tom

2025-01-16 10:23 UTC, tomHallActility commented
Hi @niccoloenginko,

I hope you are doing well. 
Have you been able to take a look at my review? 
We would like to move forward with your new additions to our catalog.

Thanks in advance,
Tom

2025-01-30 15:21 UTC, closed without merging