Update decoder of s210x and s2120
actility/device-catalog pull request #48
Opened 2023-06-30 08:19 UTC by Kway99

I have updated the driver of s210x and s2120 based on your comments. Please kindly have a check! much appreciated!

2023-06-30 08:39 UTC, mostafaibr commented
@Kway99 Thank you for the modifications. 
However the unit tests do not pass on your drivers. Please run `npm install && npm run test` to see the results and diff. 

For s210x: 
```
 FAIL  ./driver-examples.spec.js
  Decode uplink
    ✕ uplink containing only pulse counter (8 ms)

  ● Decode uplink › uplink containing only pulse counter

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 21
    + Received  +  6

      Object {
        "data": Object {
          "0": Object {
    -       "measurementId": "4097",
    -       "measurementValue": 27.2,
    -       "type": "Air Temperature",
    +       "measurementId": 3,
    +       "measurementValue": 825307.237,
    +       "type": "Measurement",
          },
          "1": Object {
    -       "measurementId": "4098",
    -       "measurementValue": "-24",
    -       "type": "Air Humidity",
    -     },
    -     "2": Object {
    -       "measurementId": "4099",
    -       "measurementValue": "-1758103807",
    -       "type": "Light Intensity",
    -     },
    -     "3": Object {
    -       "measurementId": "4190",
    -       "measurementValue": 1,
    -       "type": "UV Index",
    -     },
    -     "4": Object {
    -       "measurementId": "4105",
    -       "measurementValue": 432.8,
    -       "type": "Wind Speed",
    +       "measurementId": 1,
    +       "measurementValue": 943273.779,
    +       "type": "Measurement",
          },
        },
        "errors": Array [],
        "warnings": Array [],
      }

      24 |         // Then
      25 |         const expected = example.output
    > 26 |         expect(result).toStrictEqual(expected)
         |                        ^
      27 |       })
      28 |     }
      29 |   })

      at Object.toStrictEqual (driver-examples.spec.js:26:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.63 s
```

For s2120: 
``` 
 FAIL  ./driver-examples.spec.js
  Decode uplink
    ✕ uplink containing only pulse counter (8 ms)

  ● Decode uplink › uplink containing only pulse counter

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 21
    + Received  +  6

      Object {
        "data": Object {
          "0": Object {
    -       "measurementId": "4097",
    -       "measurementValue": 27.2,
    -       "type": "Air Temperature",
    +       "measurementId": 3,
    +       "measurementValue": 825307.237,
    +       "type": "Measurement",
          },
          "1": Object {
    -       "measurementId": "4098",
    -       "measurementValue": "-24",
    -       "type": "Air Humidity",
    -     },
    -     "2": Object {
    -       "measurementId": "4099",
    -       "measurementValue": "-1758103807",
    -       "type": "Light Intensity",
    -     },
    -     "3": Object {
    -       "measurementId": "4190",
    -       "measurementValue": 1,
    -       "type": "UV Index",
    -     },
    -     "4": Object {
    -       "measurementId": "4105",
    -       "measurementValue": 432.8,
    -       "type": "Wind Speed",
    +       "measurementId": 1,
    +       "measurementValue": 943273.779,
    +       "type": "Measurement",
          },
        },
        "errors": Array [],
        "warnings": Array [],
      }

      24 |         // Then
      25 |         const expected = example.output
    > 26 |         expect(result).toStrictEqual(expected)
         |                        ^
      27 |       })
      28 |     }
      29 |   })

      at Object.toStrictEqual (driver-examples.spec.js:26:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.63 s
```

2023-06-30 08:40 UTC, mostafaibr requested changes

2023-06-30 08:40 UTC, mostafaibr commented on vendors/sensecap/drivers/s2120/index.js
> +    bytes = Buffer.from(bytes, 'utf8').toString('hex')
```suggestion
    bytes = Buffer.from(bytes).toString('hex')
```

the input.bytes is an array of integers, thus, this conversion does not work. You should not specify the source type as 'utf8'.

2023-06-30 08:42 UTC, mostafaibr commented
In the updated drivers, the version in package.json should be updated. 
Here the modifications are bugs fix, so kindly update the version from 1.0.0 to 1.0.1

2023-07-06 06:16 UTC, Kway99 commented
Hello @mostafaibr , Thanks for your suggestion! We have updated the driver files for S210X and S2120. And we also run the unit test locally. Check this:
S210x
<img width="954" alt="企业微信截图_06c5fabf-a64a-4526-8ee1-d231a9b82b81" src="https://github.com/actility/device-catalog/assets/108512334/0d81d241-5a75-449a-b418-7f530b233243">
S2120
<img width="848" alt="企业微信截图_6e8b36c8-2e36-42c7-be92-8006af0796ff" src="https://github.com/actility/device-catalog/assets/108512334/f0700ad7-8835-4b77-84ee-1e2b4750ebb6">

2023-07-06 08:37 UTC, merged