th v4
actility/device-catalog pull request #57
Opened 2023-08-01 13:00 UTC by Logia556

th v4

2023-08-01 13:02 UTC, Logia556 commented
please pull this pull request to add th_v4 watteco device

2023-08-14 10:06 UTC, mostafaibr commented
All driver's files should be under the directory "/drivers/th_v4". so please move the files "decode.js", "batch.js", "standard.js".

2023-08-14 10:13 UTC, mostafaibr requested changes

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/package.json
> +  "name": "TH",
could we name the driver "th-v4" as now both v3 and v4 will be supported?

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/webpack.config.js
> +const path = require("path");
If you are obliged to have multiple js file for your decoder, and decided to use webpack. 

Here are the configurations to use: 

```
const path = require("path");

module.exports = {
  target: "node",
  mode: "production",
  entry: "./index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "."),
    library: "driver",
  },
};
```

in your case you could replace "index.js" by "th.js".

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/models/th_v4/model.yaml
> +name: TH
Could be named TH v4 to distinct the TH models. Now TH v3 and TH v4 would be supported.

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/metadata.json
> +  "name": "TH",
```suggestion
  "name": "th-v4",
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/metadata.json
> +  "description": "driver for TH sensor",
```suggestion
  "description": "driver for TH v4 sensor",
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/package.json
> +  "name": "TH",
```suggestion
  "name": "th-v4",
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/package.json
> +  "description": "TH captor npm packaged",
```suggestion
  "description": "TH v4 decoder npm packaged",
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/package.json
> +  }
```suggestion
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/models/th_v4/model.yaml
> +name: TH
```suggestion
name: TH v4
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/profiles/WATTECO-TH.1.0.2b_ETSI.yaml
> +id: WATTECO-TH.1.0.2b_ETSI
```suggestion
id: nke-watteco_RFGroup1_1.0.2b_classA
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +      "warnings": [""]
```suggestion
      "warnings": []
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +        ""
```suggestion
        
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +        ""
```suggestion
        
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +        ""
```suggestion
        
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +      "warnings": [""]
```suggestion
      "warnings": []
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +      "warnings": [""]
```suggestion
      "warnings": []
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +        ""
```suggestion
        
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +        ""
```suggestion
        
```

2023-08-14 10:13 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +      "warnings": [""]
```suggestion
      "warnings": []
```

2023-08-14 10:21 UTC, mostafaibr commented
Please do not hesitate to get back to us if you have any doubt about the changes to do, we could organize a short session to fix all the issues together.

2023-08-14 12:59 UTC, mostafaibr commented on vendors/watteco/drivers/decode.js
> +                    warnings: [""],
```suggestion
                    warnings: [],
```

2023-08-14 12:59 UTC, mostafaibr commented on vendors/watteco/drivers/decode.js
> +            warnings: [""],
```suggestion
            warnings: [],
```

2023-08-14 13:00 UTC, mostafaibr commented on vendors/watteco/drivers/th_v4/examples.json
> +      "warnings": [["alarm triggered"]]
```suggestion
      "warnings": ["alarm triggered"]
```

2023-08-16 16:29 UTC, mostafaibr commented
Hello @Logia556 ,

I wanted to apply the suggested changes on your PR, but did not have the access.

I have created a new PR so you can check it: https://github.com/actility/device-catalog/pull/61

In that case, no need to fix anything from your side, if you agree on my PR, we could directly merge it and close this one.
A new version of device profiles and drivers would be released before the end of the week. so If you want to include your modifications, please take a look on [this PR](https://github.com/actility/device-catalog/pull/61) and get back to me as soon as possible. 

Thank you

2023-08-17 08:42 UTC, closed without merging