Watteco devices codec with decode_uplink
actility/device-catalog pull request #73
Opened 2023-09-15 10:41 UTC by Logia556

contains the WATTECO devices. Thank you for reviewing this pull request and give feedbacks

2023-09-22 14:07 UTC, mostafaibr requested changes
Hello @Logia556, 

Thank you for your contribution. 

I have added comments on decode.js and standard.js about `warnings` with code suggestions.
In addition, added a comment on the examples.json file of Clos'o driver about the same issue, this comment applies to all other drivers. 

Can you please fix that in order to be able to merge your PR and integrate the devices into the next release as soon as possible?

The PR has conflicts with the main branch, please consider resolving them. 

Thank you.

2023-09-22 14:07 UTC, mostafaibr commented on vendors/watteco/drivers/decode.js
> +                    warnings: [""],
```suggestion
                    warnings: [],
```

2023-09-22 14:07 UTC, mostafaibr commented on vendors/watteco/drivers/decode.js
> +                    warnings: [""],
```suggestion
                    warnings: [],
```

2023-09-22 14:07 UTC, mostafaibr commented on vendors/watteco/drivers/standard.js
> +    let warning = [""];
```suggestion
    let warning = [];
```

2023-09-22 14:21 UTC, mostafaibr commented
Another small remark, in the driver there is a lot of console.log statements, could you remove that also?

2023-09-25 08:02 UTC, Logia556 commented
Empty strings in warning, and console.log() removed.
Conflicts resolved.

2023-09-25 08:41 UTC, Logia556 reviewed
empty strings removed in warnings

2023-09-25 14:54 UTC, mostafaibr approved these changes

2023-09-25 14:54 UTC, merged