Update of Volley Boast vendor
actility/device-catalog pull request #85
Opened 2023-10-10 19:46 UTC by mvujovic-vb

2023-10-13 15:54 UTC, tomHallActility commented on vendors/volley_boast/drivers/vobo-decoder/driver.yaml
You don't need to worry about driver files, we will add them ourselves.

2023-10-13 15:58 UTC, tomHallActility commented on vendors/volley_boast/models/gp-1_v2/model.yaml
The "product" field is deprecated, can you remove it (lines 8 to 10), please?
Also, since we haven't updated the driver yet, you should remove the protocolId value and the sensors at the end (we can add them ourselves).

2023-10-13 16:07 UTC, tomHallActility commented on vendors/volley_boast/profiles/volley-boast-sl_RFGroup2_1.0.4_classA.yaml
Please prefer copying and pasting your profiles from "/template/Generic Profiles Templates" and modifying the files accordingly (lora-generic -> msight, changing the TX Power values for instance, or the activationByPersonalization and overTheAirActivation).

Please apply this suggestion to all your new profiles, it prevents inconsistency and deprecated fields. Thank you.

2023-10-13 16:11 UTC, tomHallActility requested changes
Thank you for taking the time to review and modify some of these files.
It shouldn't be too long before your device models are operational on our platforms.

2023-10-16 15:08 UTC, mvujovic-vb commented on vendors/volley_boast/drivers/vobo-decoder/driver.yaml
Noted and removed in latest commit

2023-10-16 15:10 UTC, mvujovic-vb commented on vendors/volley_boast/profiles/volley-boast-sl_RFGroup2_1.0.4_classA.yaml
I did comparison of our profiles and the one from template and I don't see any structural difference except from values itself which is expected. Can you guide me in more details what is wrong with our new profiles?

2023-10-16 15:20 UTC, tomHallActility commented on vendors/volley_boast/models/gp-1_v2/model.yaml
The sensors are meant to standardise the measured values taken from the output of the driver, so there are specific units, labels and rules set by Actility which are applied depending on the driver's output values.

2023-10-16 16:13 UTC, tomHallActility commented on vendors/volley_boast/profiles/volley-boast-sl_RFGroup2_1.0.4_classA.yaml
You are correct that in your files, only some field values are different from the templates. 

There are only a few things to change:

Please change your profile's id values and file names (don't forget to update their references as well, please): 
- volley-boast-sl_RFGroup2_1.0.4_classA -> volley-boast_RFGroup2_1.0.4-RP2-1.0.3_classA
- volley-boast-xp_RFGroup2_1.0.4_classA -> volley-boast_RFGroup2_1.0.4-RP2-1.0.3_classC

And delete the following profiles (and their references):
- volley-boast-tc_RFGroup2_1.0.4_classA
- volley-boast-xx_RFGroup2_1.0.4_classA

That way profiles are kept generic and reusable for other models in the future as well.
Thank you in advance.

2023-10-16 16:16 UTC, tomHallActility commented on vendors/volley_boast/drivers/vobo-decoder/driver.yaml
Thank you.

2023-10-16 16:24 UTC, mvujovic-vb commented on vendors/volley_boast/profiles/volley-boast-sl_RFGroup2_1.0.4_classA.yaml
Updated according to your request. Please check latest commit

2023-10-16 16:29 UTC, mvujovic-vb commented on vendors/volley_boast/models/gp-1_v2/model.yaml
Sensor lists are removed from all models in the latest commit. Our devices are bridges that can read various types of sensors and then report sensor values in any type of engineering units, so this sounds like it could be a limitation for the Actility LNS.

2023-10-17 08:27 UTC, tomHallActility approved these changes

2023-10-17 08:32 UTC, merged